name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print the triggering event
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Print the OS of the runner
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Print the branch name that the workflow runs on
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: ls ${{ github.workspace }}